// Generated by tools/export_policy.py -- do not edit.
//   actor  kxrl2g_walk.onnx
//   task   Kxrl2g-Walk
//   layers 77 -> 256 -> 128 -> 64 -> 22 (ELU)
//   checked against onnxruntime to 1.97e-06
//   control  50 Hz (overridden; calibration.yaml says 50)

#pragma once

#include <stdint.h>

// Shape of the network.
#define POLICY_KXRL2GWALK_OBS_DIM 77
#define POLICY_KXRL2GWALK_ACT_DIM 22
#define POLICY_KXRL2GWALK_LAYERS 4
#define POLICY_KXRL2GWALK_WIDEST_LAYER 256
// Floats in the weight matrices and biases together, so a build that
// copies them into RAM can size its buffer without a number typed in
// by hand that a retrain could make stale.
#define POLICY_KXRL2GWALK_WEIGHT_FLOATS 62550

// Control loop constants, taken from deploy_spec.json and
// calibration.yaml so the firmware cannot drift from the host tools.
#define POLICY_KXRL2GWALK_ACTION_SCALE 0.25f
#define POLICY_KXRL2GWALK_PHASE_PERIOD_S 0.6f
#define POLICY_KXRL2GWALK_PHASE_STAND_THRESHOLD 0.1f

// The command band the actor was actually trained on. Outside it the
// policy is extrapolating, and nothing in the observation tells it so
// -- it simply produces a target for a speed it has never had to
// achieve. The firmware clamps to these rather than to whatever the
// operator's stick can reach, which for one policy here was three
// times the trained speed.
#define POLICY_KXRL2GWALK_COMMAND_VX_MIN 0.159693333f
#define POLICY_KXRL2GWALK_COMMAND_VX_MAX 0.319386667f
#define POLICY_KXRL2GWALK_COMMAND_WZ_MAX 0.0f
#define POLICY_KXRL2GWALK_COMMAND_RANGES_KNOWN 1
// Fraction of training environments that were given a zero command.
// Zero here means the actor has never been asked to stand still, so a
// stick at rest is outside what it was trained on.
#define POLICY_KXRL2GWALK_STANDING_FRACTION 0.0f

#define POLICY_KXRL2GWALK_CONTROL_HZ 50.0f
#define POLICY_KXRL2GWALK_SERVO_FRAME_COUNT 6
// Getting to the home stance before the policy starts: slow, because
// nothing about it is time-critical and the hand may be starting from
// a collapsed pose.
#define POLICY_KXRL2GWALK_HOME_FRAME_COUNT 200
// Holding stiffness written into every servo before running. The
// board comes set to 127, which buzzed on this hand.
#define POLICY_KXRL2GWALK_SERVO_STRETCH 90
#define POLICY_KXRL2GWALK_JOINT_VEL_WINDOW_S 0.08f

// Where each observation term starts, so the firmware assembles the
// vector in the order the actor was trained on rather than in the
// order it happens to compute the terms.
#define POLICY_KXRL2GWALK_OBS_BASE_ANG_VEL_START 0
#define POLICY_KXRL2GWALK_OBS_BASE_ANG_VEL_DIM 3
#define POLICY_KXRL2GWALK_OBS_PROJECTED_GRAVITY_START 3
#define POLICY_KXRL2GWALK_OBS_PROJECTED_GRAVITY_DIM 3
#define POLICY_KXRL2GWALK_OBS_COMMAND_START 6
#define POLICY_KXRL2GWALK_OBS_COMMAND_DIM 3
#define POLICY_KXRL2GWALK_OBS_PHASE_START 9
#define POLICY_KXRL2GWALK_OBS_PHASE_DIM 2
#define POLICY_KXRL2GWALK_OBS_JOINT_POS_START 11
#define POLICY_KXRL2GWALK_OBS_JOINT_POS_DIM 22
#define POLICY_KXRL2GWALK_OBS_JOINT_VEL_START 33
#define POLICY_KXRL2GWALK_OBS_JOINT_VEL_DIM 22
#define POLICY_KXRL2GWALK_OBS_ACTIONS_START 55
#define POLICY_KXRL2GWALK_OBS_ACTIONS_DIM 22

// Home pose in URDF radians: the action is an offset from this, and
// joint_pos is reported relative to it.
static const float kPolicyHomeRadKxrl2Gwalk[22] = {
    0.0f, 0.000996000017f, -0.000379000005f, -0.00530700013f, -0.000403999991f, -0.000368000008f, 3.30000003e-05f, 0.000560000015f,
    0.0024029999f, 0.00244700001f, 0.00198299997f, 0.000402000005f, -0.000377999997f, 0.00530799991f, -0.000403999991f, -0.000368000008f,
    3.30000003e-05f, -8.49999997e-05f, 0.0024590001f, 0.00258300011f, 0.00219599996f, 7.50000036e-05f,
};

static const float kPolicyJointLowRadKxrl2Gwalk[22] = {
    -2.67035413f, -1.88495994f, -2.82743096f, -0.335976124f, -2.67035413f, -1.57079697f, -1.57079697f, -2.12231588f,
    -2.15984058f, -1.51843691f, -1.64933991f, -2.67035413f, -2.82743096f, -3.04123688f, -2.67035413f, -1.57079697f,
    -1.57079697f, -2.12231588f, -2.15984058f, -1.51843691f, -1.64933991f, -2.67035413f,
};

static const float kPolicyJointHighRadKxrl2Gwalk[22] = {
    2.67035413f, 1.88495994f, 2.82743096f, 3.04123688f, 2.67035413f, 1.57079697f, 1.57079697f, 2.0874157f,
    1.37445045f, 2.56563711f, 1.64933991f, 2.67035413f, 2.82743096f, 0.335976124f, 2.67035413f, 1.57079697f,
    1.57079697f, 2.0874157f, 1.37445045f, 2.56563711f, 1.64933991f, 2.67035413f,
};

// RCB-4 servo id per joint, in joint_order. NOT sorted: this is the
// policy's own order, and the board wants ids ascending, so a caller
// writing a servo command has to reorder.
static const uint8_t kPolicyServoIdsKxrl2Gwalk[22] = {
    255, 255, 3, 5, 7, 255, 255, 9, 11, 13, 15, 17, 2, 4, 6, 255,
    255, 8, 10, 12, 14, 16,
};

// Gravity in the root frame for this policy's own stance, from
// home_base.quat_wxyz. Used only when there is no IMU; a transition
// changes the attitude and cannot be represented by it at all.
static const float kPolicyStanceGravityKxrl2Gwalk[3] = {
    -0.00711568948f, 0.00031206069f, -0.999974634f,
};

// v_gyro = R_root_to_gyro @ v_root. base_ang_vel is observed in the
// URDF base link frame while projected_gravity is in root, and the
// two are not the same frame -- getting this wrong is silent.
static const float kPolicyRootToGyroKxrl2Gwalk[9] = {
    1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f,
    1.0f,
};
