// Generated by tools/export_policy.py -- do not edit.
//   actor  kxrl6_walk.onnx
//   task   Kxrl6-Walk
//   layers 65 -> 256 -> 128 -> 64 -> 18 (ELU)
//   checked against onnxruntime to 2.38e-06
//   control  50 Hz (overridden; calibration.yaml says 50)

#pragma once

#include <stdint.h>

// Shape of the network.
#define POLICY_KXRL6WALK_OBS_DIM 65
#define POLICY_KXRL6WALK_ACT_DIM 18
#define POLICY_KXRL6WALK_LAYERS 4
#define POLICY_KXRL6WALK_WIDEST_LAYER 256
// Floats in the weight matrices and biases together, so a build that
// copies them into RAM can size its buffer without a number typed in
// by hand that a retrain could make stale.
#define POLICY_KXRL6WALK_WEIGHT_FLOATS 59218

// Control loop constants, taken from deploy_spec.json and
// calibration.yaml so the firmware cannot drift from the host tools.
#define POLICY_KXRL6WALK_ACTION_SCALE 0.25f
#define POLICY_KXRL6WALK_PHASE_PERIOD_S 0.6f
#define POLICY_KXRL6WALK_PHASE_STAND_THRESHOLD 0.1f

// The command band the actor was actually trained on. Outside it the
// policy is extrapolating, and nothing in the observation tells it so
// -- it simply produces a target for a speed it has never had to
// achieve. The firmware clamps to these rather than to whatever the
// operator's stick can reach, which for one policy here was three
// times the trained speed.
#define POLICY_KXRL6WALK_COMMAND_VX_MIN 0.175f
#define POLICY_KXRL6WALK_COMMAND_VX_MAX 0.35f
#define POLICY_KXRL6WALK_COMMAND_WZ_MAX 0.0f
#define POLICY_KXRL6WALK_COMMAND_RANGES_KNOWN 1
// Fraction of training environments that were given a zero command.
// Zero here means the actor has never been asked to stand still, so a
// stick at rest is outside what it was trained on.
#define POLICY_KXRL6WALK_STANDING_FRACTION 0.0f

#define POLICY_KXRL6WALK_CONTROL_HZ 50.0f
#define POLICY_KXRL6WALK_SERVO_FRAME_COUNT 6
// Getting to the home stance before the policy starts: slow, because
// nothing about it is time-critical and the hand may be starting from
// a collapsed pose.
#define POLICY_KXRL6WALK_HOME_FRAME_COUNT 200
// Holding stiffness written into every servo before running. The
// board comes set to 127, which buzzed on this hand.
#define POLICY_KXRL6WALK_SERVO_STRETCH 90
#define POLICY_KXRL6WALK_JOINT_VEL_WINDOW_S 0.08f

// Where each observation term starts, so the firmware assembles the
// vector in the order the actor was trained on rather than in the
// order it happens to compute the terms.
#define POLICY_KXRL6WALK_OBS_BASE_ANG_VEL_START 0
#define POLICY_KXRL6WALK_OBS_BASE_ANG_VEL_DIM 3
#define POLICY_KXRL6WALK_OBS_PROJECTED_GRAVITY_START 3
#define POLICY_KXRL6WALK_OBS_PROJECTED_GRAVITY_DIM 3
#define POLICY_KXRL6WALK_OBS_COMMAND_START 6
#define POLICY_KXRL6WALK_OBS_COMMAND_DIM 3
#define POLICY_KXRL6WALK_OBS_PHASE_START 9
#define POLICY_KXRL6WALK_OBS_PHASE_DIM 2
#define POLICY_KXRL6WALK_OBS_JOINT_POS_START 11
#define POLICY_KXRL6WALK_OBS_JOINT_POS_DIM 18
#define POLICY_KXRL6WALK_OBS_JOINT_VEL_START 29
#define POLICY_KXRL6WALK_OBS_JOINT_VEL_DIM 18
#define POLICY_KXRL6WALK_OBS_ACTIONS_START 47
#define POLICY_KXRL6WALK_OBS_ACTIONS_DIM 18

// Home pose in URDF radians: the action is an offset from this, and
// joint_pos is reported relative to it.
static const float kPolicyHomeRadKxrl6Walk[18] = {
    -1.99999999e-06f, 0.526253998f, 0.31329301f, 3.99999999e-06f, -0.508351982f, -0.327567995f, -0.363267004f, -0.693069994f,
    0.00522600021f, -0.0f, 0.526349008f, 0.313342005f, 0.0f, -0.508451998f, -0.327618986f, 0.363265008f,
    0.693490028f, -0.00474799983f,
};

static const float kPolicyJointLowRadKxrl6Walk[18] = {
    -1.75929296f, -2.67035413f, -2.67035413f, -1.75929296f, -2.67035413f, -2.67035413f, -1.75929296f, -2.67035413f,
    -2.67035413f, -1.75929296f, -2.67035413f, -2.67035413f, -1.75929296f, -2.67035413f, -2.67035413f, -1.75929296f,
    -2.67035413f, -2.67035413f,
};

static const float kPolicyJointHighRadKxrl6Walk[18] = {
    1.75929296f, 2.67035413f, 2.67035413f, 1.75929296f, 2.67035413f, 2.67035413f, 1.75929296f, 2.67035413f,
    2.67035413f, 1.75929296f, 2.67035413f, 2.67035413f, 1.75929296f, 2.67035413f, 2.67035413f, 1.75929296f,
    2.67035413f, 2.67035413f,
};

// RCB-4 servo id per joint, in joint_order. NOT sorted: this is the
// policy's own order, and the board wants ids ascending, so a caller
// writing a servo command has to reorder.
static const uint8_t kPolicyServoIdsKxrl6Walk[18] = {
    3, 5, 7, 15, 17, 19, 9, 11, 13, 2, 4, 6, 14, 16, 18, 8,
    10, 12,
};

// Gravity in the root frame for this policy's own stance, from
// home_base.quat_wxyz. Used only when there is no IMU; a transition
// changes the attitude and cannot be represented by it at all.
static const float kPolicyStanceGravityKxrl6Walk[3] = {
    -0.00263999214f, 0.00018007638f, -0.999996499f,
};

// v_gyro = R_root_to_gyro @ v_root. base_ang_vel is observed in the
// URDF base link frame while projected_gravity is in root, and the
// two are not the same frame -- getting this wrong is silent.
static const float kPolicyRootToGyroKxrl6Walk[9] = {
    1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f,
    1.0f,
};
