cmake_minimum_required(VERSION 3.0.2)
project(euslisp)
find_package(catkin REQUIRED)

# JSKEUS_DIR is given by "make roseus" (catkin config --cmake-args)
if(NOT JSKEUS_DIR)
  set(JSKEUS_DIR $ENV{HOME}/jskeus)
endif()
if(NOT EXISTS ${JSKEUS_DIR}/eus/include/eus.h)
  message(FATAL_ERROR "${JSKEUS_DIR}/eus/include/eus.h not found, run make jskeus in kxreus")
endif()
execute_process(COMMAND uname -m OUTPUT_VARIABLE _arch OUTPUT_STRIP_TRAILING_WHITESPACE)
if(_arch STREQUAL "x86_64")
  set(ARCHDIR Linux64)
elseif(_arch STREQUAL "aarch64" OR _arch MATCHES "^arm")
  set(ARCHDIR LinuxARM)
else()
  set(ARCHDIR Linux)
endif()

catkin_package(CFG_EXTRAS euslisp-extras.cmake)
catkin_add_env_hooks(99.euslisp SHELLS sh DIRECTORY ${PROJECT_SOURCE_DIR}/env-hooks)
