
<package format="2">
  <name>kxrl4d1</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for kxrl4d1</p>
  </description>
  <maintainer email="euslisp@jsk.t.u-tokyo.ac.jp">Euslisp developer</maintainer>
  <license>Euslisp</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>roslaunch</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz</depend>
  <depend>joint_state_publisher_gui</depend>
  <export>
    <architecture_independent />
  </export>
</package>
