// Generated by tools/export_policy.py -- do not edit.
//   actor  wheeledhand_legs_walk.onnx
//   task   Wheeledhand_legs-Walk
//   layers 68 -> 256 -> 128 -> 64 -> 19 (ELU)
//   checked against onnxruntime to 4.77e-06
//   control  30 Hz (overridden; calibration.yaml says 30)

#pragma once

#include <stdint.h>

// Shape of the network.
#define POLICY_LEGS_OBS_DIM 68
#define POLICY_LEGS_ACT_DIM 19
#define POLICY_LEGS_LAYERS 4
#define POLICY_LEGS_WIDEST_LAYER 256
// Floats in the weight matrices and biases together, so a build that
// copies them into RAM can size its buffer without a number typed in
// by hand that a retrain could make stale.
#define POLICY_LEGS_WEIGHT_FLOATS 60051

// Control loop constants, taken from deploy_spec.json and
// calibration.yaml so the firmware cannot drift from the host tools.
#define POLICY_LEGS_ACTION_SCALE 0.25f
#define POLICY_LEGS_PHASE_PERIOD_S 0.6f
#define POLICY_LEGS_PHASE_STAND_THRESHOLD 0.1f

// The command band the actor was actually trained on. Outside it the
// policy is extrapolating, and nothing in the observation tells it so
// -- it simply produces a target for a speed it has never had to
// achieve. The firmware clamps to these rather than to whatever the
// operator's stick can reach, which for one policy here was three
// times the trained speed.
#define POLICY_LEGS_COMMAND_VX_MIN 0.125f
#define POLICY_LEGS_COMMAND_VX_MAX 0.25f
#define POLICY_LEGS_COMMAND_WZ_MAX 0.0f
#define POLICY_LEGS_COMMAND_RANGES_KNOWN 1
// Fraction of training environments that were given a zero command.
// Zero here means the actor has never been asked to stand still, so a
// stick at rest is outside what it was trained on.
#define POLICY_LEGS_STANDING_FRACTION 0.0f

#define POLICY_LEGS_CONTROL_HZ 30.0f
#define POLICY_LEGS_SERVO_FRAME_COUNT 6
// Getting to the home stance before the policy starts: slow, because
// nothing about it is time-critical and the hand may be starting from
// a collapsed pose.
#define POLICY_LEGS_HOME_FRAME_COUNT 200
// Holding stiffness written into every servo before running. The
// board comes set to 127, which buzzed on this hand.
#define POLICY_LEGS_SERVO_STRETCH 90
#define POLICY_LEGS_JOINT_VEL_WINDOW_S 0.08f

// Where each observation term starts, so the firmware assembles the
// vector in the order the actor was trained on rather than in the
// order it happens to compute the terms.
#define POLICY_LEGS_OBS_BASE_ANG_VEL_START 0
#define POLICY_LEGS_OBS_BASE_ANG_VEL_DIM 3
#define POLICY_LEGS_OBS_PROJECTED_GRAVITY_START 3
#define POLICY_LEGS_OBS_PROJECTED_GRAVITY_DIM 3
#define POLICY_LEGS_OBS_COMMAND_START 6
#define POLICY_LEGS_OBS_COMMAND_DIM 3
#define POLICY_LEGS_OBS_PHASE_START 9
#define POLICY_LEGS_OBS_PHASE_DIM 2
#define POLICY_LEGS_OBS_JOINT_POS_START 11
#define POLICY_LEGS_OBS_JOINT_POS_DIM 19
#define POLICY_LEGS_OBS_JOINT_VEL_START 30
#define POLICY_LEGS_OBS_JOINT_VEL_DIM 19
#define POLICY_LEGS_OBS_ACTIONS_START 49
#define POLICY_LEGS_OBS_ACTIONS_DIM 19

// Home pose in URDF radians: the action is an offset from this, and
// joint_pos is reported relative to it.
static const float kPolicyHomeRadLegs[19] = {
    0.128941998f, 1.21126497f, 0.926759005f, 0.230819002f, 0.128935993f, 1.21228397f, 0.928520024f, 0.231670007f,
    0.128932998f, 1.21246505f, 0.928833008f, 0.231821001f, 0.128941998f, 1.210783f, 0.92592603f, 0.230416998f,
    1.68690395f, 0.626688004f, 0.323431998f,
};

static const float kPolicyJointLowRadLegs[19] = {
    -1.5f, -0.698000014f, -1.77999997f, -1.77999997f, -1.5f, -0.698000014f, -1.77999997f, -1.77999997f,
    -1.5f, -0.698000014f, -1.77999997f, -1.77999997f, -1.5f, -0.698000014f, -1.77999997f, -1.77999997f,
    -2.35599995f, -1.77999997f, -1.77999997f,
};

static const float kPolicyJointHighRadLegs[19] = {
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    2.35599995f, 1.77999997f, 1.77999997f,
};

// RCB-4 servo id per joint, in joint_order. NOT sorted: this is the
// policy's own order, and the board wants ids ascending, so a caller
// writing a servo command has to reorder.
static const uint8_t kPolicyServoIdsLegs[19] = {
    6, 4, 2, 20, 30, 28, 34, 26, 27, 25, 23, 13, 17, 15, 1, 11,
    33, 9, 19,
};

// Gravity in the root frame for this policy's own stance, from
// home_base.quat_wxyz. Used only when there is no IMU; a transition
// changes the attitude and cannot be represented by it at all.
static const float kPolicyStanceGravityLegs[3] = {
    0.0092337119f, 0.0026426173f, -0.999953876f,
};

// v_gyro = R_root_to_gyro @ v_root. base_ang_vel is observed in the
// URDF base link frame while projected_gravity is in root, and the
// two are not the same frame -- getting this wrong is silent.
static const float kPolicyRootToGyroLegs[9] = {
    -0.0f, -1.0f, 0.0f, -0.0f, 0.0f, -1.0f, 1.0f, -0.0f,
    -0.0f,
};
