"""Auto-configure an arbitrary KXR modular robot from its URDF + eus2yaml limb map.

KXR (Kondo Kagaku) robots are built from a small catalogue of servo modules
(crotch/knee/ankle/shoulder/elbow/wrist/neck/gripper) that ``kxreus`` (the
Euslisp modular-robot toolkit these assets come from) assembles into many
different bodies -- 2 or 4 arms, 2 legs with anywhere from 2 to 5 leg DOF, with
or without a head/gripper. Every joint shares ONE real servo spec (0.656248
N*m stall, 7.48 rad/s -- the same actuator the walking-hand-rl hand uses), and
every URDF follows the same naming convention: a joint's name equals its child
link's name, and it is prefixed by which limb it belongs to (``lleg-`` /
``rleg-`` / ``larm-`` / ``rarm-`` / ``lmarm-`` / ``rmarm-`` / ``head-``).

Rather than write one robot_cfg.py per body (as walking-hand-rl does for its
single hand), this module PARSES that structure -- primarily from the
``kxreus/yamls/<name>.yaml`` limb map ``kxreus`` itself generates, with a
URDF-naming-convention fallback for a robot that has no yaml -- so a new KXR
body needs zero new code, only its name added to ``ROBOTS``. This is the
point of the exercise: the same task recipe (env_cfgs.py) trains stand-up and
walking for whichever leg/arm/head combination a robot happens to have.
"""

from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

import yaml

# Where the kxreus checkout lives. It is a sibling checkout, not part of this
# repo (the URDFs and limb-map yamls are generated by kxreus / eus2yaml).
KXREUS_ROOT = Path(os.environ.get("KXREUS_ROOT", "~/kxreus")).expanduser()
URDF_ROOT = KXREUS_ROOT / "urdfs"
YAML_ROOT = KXREUS_ROOT / "yamls"

# The four asked for explicitly. Any other directory under kxreus/urdfs with at
# least one leg (an "lleg"/"rleg" limb with >=1 joint) also works untouched --
# see `discover_robots()` -- this tuple is just the default training set.
DEFAULT_ROBOTS: tuple[str, ...] = ("kxrl4d", "kxrl4t", "kxrl2g", "kxrl6")

# All joints across the KXR catalogue share this spec (measured, see
# walking-hand-rl/walking_hand_rl/robot_cfg.py for the same number on the hand).
# Effort is NEVER inflated: only motions the real servo can produce are
# learnable, so a policy that works in sim is deployable.
JOINT_EFFORT_NM = float(os.environ.get("KXR_EFFORT", "0.656248"))
JOINT_VELOCITY_RAD_S = 7.47998

_LEG_KEY_SUFFIX = "leg"  # "lleg" / "rleg"
_SKIP_YAML_KEYS = ("angle-vector",)


@dataclass
class LimbSpec:
  joints: tuple[str, ...]  # base -> tip, KXR convention: joint name == child link name

  @property
  def foot_link(self) -> str:
    """The terminal link of a leg chain -- ankle if the leg has one, else knee."""
    return self.joints[-1]


@dataclass
class RobotSpec:
  name: str
  urdf_path: Path
  torso_link: str
  legs: dict[str, LimbSpec]        # "lleg" / "rleg" -> chain
  upper: dict[str, LimbSpec]       # arms / mid-arms / head, whatever exists
  all_joints: tuple[str, ...]      # every actuated joint, legs first then upper

  @property
  def foot_links(self) -> tuple[str, ...]:
    return tuple(leg.foot_link for leg in self.legs.values())

  @property
  def leg_dof_names(self) -> dict[str, str]:
    """joint name -> DOF role (hip_yaw/hip_roll/hip_pitch/knee/ankle_pitch/ankle_roll),
    inferred from the joint-name suffix (KXR: ``-y``/``-r``/``-p`` = yaw/roll/pitch,
    and ordinal position within the leg chain: crotch* is the hip, then knee, then
    ankle*). Used only to build the pose-regularization std map generically."""
    roles: dict[str, str] = {}
    for leg in self.legs.values():
      seen_crotch = 0
      seen_ankle = 0
      for j in leg.joints:
        segment = j.split("-")[1] if len(j.split("-")) > 2 else j.split("-")[0]
        axis = j.rsplit("-", 1)[-1]
        if "crotch" in j:
          seen_crotch += 1
          roles[j] = {"y": "hip_yaw", "r": "hip_roll", "p": "hip_pitch"}.get(axis, "hip")
        elif "knee" in j:
          roles[j] = "knee"
        elif "ankle" in j:
          seen_ankle += 1
          roles[j] = {"y": "ankle_yaw", "r": "ankle_roll", "p": "ankle_pitch"}.get(axis, "ankle")
        else:
          roles[j] = segment
    return roles


def _urdf_root_link(urdf_path: Path) -> str:
  """The one link that is never a joint's child -- the floating base."""
  tree = ET.parse(urdf_path)
  robot = tree.getroot()
  children = {j.find("child").get("link") for j in robot.iter("joint")}
  links = [link.get("name") for link in robot.findall("link")]
  roots = [name for name in links if name not in children]
  if len(roots) != 1:
    raise ValueError("{}: expected exactly one root link, found {}".format(urdf_path, roots))
  return roots[0]


def _urdf_joint_names(urdf_path: Path) -> list[str]:
  tree = ET.parse(urdf_path)
  robot = tree.getroot()
  return [j.get("name") for j in robot.findall("joint") if j.get("type") != "fixed"]


def _limbs_from_yaml(yaml_path: Path) -> dict[str, LimbSpec]:
  with yaml_path.open() as f:
    doc = yaml.safe_load(f)
  limbs: dict[str, LimbSpec] = {}
  for key, value in doc.items():
    if key in _SKIP_YAML_KEYS or key.endswith("-end-coords"):
      continue
    if not isinstance(value, list):
      continue
    joints = tuple(list(entry.keys())[0] for entry in value)
    if joints:
      limbs[key] = LimbSpec(joints=joints)
  return limbs


# Fallback when a robot has no kxreus yaml: bucket joints by the prefix before
# the first "-", which is exactly the limb tag every KXR URDF joint carries.
_PREFIX_TO_LIMB = {
  "lleg": "lleg", "rleg": "rleg",
  "larm": "larm", "rarm": "rarm",
  "lmarm": "lmarm", "rmarm": "rmarm",
  "head": "head",
}


def _limbs_from_urdf_naming(joint_names: list[str]) -> dict[str, LimbSpec]:
  buckets: dict[str, list[str]] = {}
  for name in joint_names:
    prefix = name.split("-", 1)[0]
    limb = _PREFIX_TO_LIMB.get(prefix)
    if limb is None:
      continue
    buckets.setdefault(limb, []).append(name)
  return {k: LimbSpec(joints=tuple(v)) for k, v in buckets.items()}


def load_robot_spec(name: str) -> RobotSpec:
  urdf_path = URDF_ROOT / name / "urdf" / "{}.urdf".format(name)
  if not urdf_path.exists():
    raise FileNotFoundError(
      "{} not found -- is {} a directory under {}?".format(urdf_path, name, URDF_ROOT))

  yaml_path = YAML_ROOT / "{}.yaml".format(name)
  if yaml_path.exists():
    limbs = _limbs_from_yaml(yaml_path)
  else:
    limbs = _limbs_from_urdf_naming(_urdf_joint_names(urdf_path))

  legs = {k: v for k, v in limbs.items() if k.endswith(_LEG_KEY_SUFFIX)}
  if not legs:
    raise ValueError("{}: no leg limb found (have {}) -- not a leg-type robot".format(
      name, sorted(limbs)))
  upper = {k: v for k, v in limbs.items() if k not in legs}

  torso_link = _urdf_root_link(urdf_path)
  all_joints = tuple(j for limb in limbs.values() for j in limb.joints)

  return RobotSpec(
    name=name,
    urdf_path=urdf_path,
    torso_link=torso_link,
    legs=legs,
    upper=upper,
    all_joints=all_joints,
  )


def discover_robots() -> tuple[str, ...]:
  """Every directory under kxreus/urdfs that parses as a leg-type robot."""
  found = []
  if not URDF_ROOT.is_dir():
    return ()
  for d in sorted(URDF_ROOT.iterdir()):
    if not (d / "urdf" / "{}.urdf".format(d.name)).exists():
      continue
    try:
      load_robot_spec(d.name)
    except Exception:
      continue
    found.append(d.name)
  return tuple(found)


if __name__ == "__main__":
  import sys

  names = sys.argv[1:] or list(DEFAULT_ROBOTS)
  for name in names:
    spec = load_robot_spec(name)
    print("{}: torso={} legs={} feet={} upper_limbs={} n_joints={}".format(
      spec.name, spec.torso_link, {k: v.joints for k, v in spec.legs.items()},
      spec.foot_links, sorted(spec.upper), len(spec.all_joints)))
