/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef EI_TFLITE_MODEL_OPS_DEFINES_H
#define EI_TFLITE_MODEL_OPS_DEFINES_H

#define EI_TFLITE_DISABLE_SOFTMAX_IN_U8     1
#define EI_TFLITE_DISABLE_SOFTMAX_IN_I16    1
#define EI_TFLITE_DISABLE_SOFTMAX_IN_F32    1
#define EI_TFLITE_DISABLE_SOFTMAX_IN_BOOL   1
#define EI_TFLITE_DISABLE_SOFTMAX_OUT_U8    1
#define EI_TFLITE_DISABLE_SOFTMAX_OUT_I16   1
#define EI_TFLITE_DISABLE_SOFTMAX_OUT_F32   1
#define EI_TFLITE_DISABLE_SOFTMAX_OUT_BOOL  1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_IN_U8     1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_IN_I16    1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_IN_F32    1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_IN_BOOL   1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_OUT_U8    1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_OUT_I16   1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_OUT_F32   1
#define EI_TFLITE_DISABLE_FULLY_CONNECTED_OUT_BOOL  1
#define EI_TFLITE_DISABLE_CONV_2D_IN_U8     1
#define EI_TFLITE_DISABLE_CONV_2D_IN_I16    1
#define EI_TFLITE_DISABLE_CONV_2D_IN_F32    1
#define EI_TFLITE_DISABLE_CONV_2D_IN_BOOL   1
#define EI_TFLITE_DISABLE_CONV_2D_OUT_U8    1
#define EI_TFLITE_DISABLE_CONV_2D_OUT_I16   1
#define EI_TFLITE_DISABLE_CONV_2D_OUT_F32   1
#define EI_TFLITE_DISABLE_CONV_2D_OUT_BOOL  1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_IN_U8     1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_IN_I16    1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_IN_F32    1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_IN_BOOL   1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_OUT_U8    1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_OUT_I16   1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_OUT_F32   1
#define EI_TFLITE_DISABLE_MAX_POOL_2D_OUT_BOOL  1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_IN_U8     1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_IN_I8     1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_IN_I16    1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_IN_F32    1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_IN_BOOL   1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_OUT_U8    1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_OUT_I8    1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_OUT_I16   1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_OUT_F32   1
#define EI_TFLITE_DISABLE_DEPTHWISE_CONV_2D_OUT_BOOL  1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_IN_U8     1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_IN_I8     1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_IN_I16    1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_IN_F32    1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_IN_BOOL   1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_OUT_U8    1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_OUT_I8    1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_OUT_I16   1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_OUT_F32   1
#define EI_TFLITE_DISABLE_AVERAGE_POOL_2D_OUT_BOOL  1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_IN_U8     1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_IN_I8     1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_IN_I16    1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_IN_F32    1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_IN_BOOL   1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_OUT_U8    1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_OUT_I8    1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_OUT_I16   1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_OUT_F32   1
#define EI_TFLITE_DISABLE_STRIDED_SLICE_OUT_BOOL  1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_IN_U8     1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_IN_I8     1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_IN_I16    1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_IN_F32    1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_IN_BOOL   1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_OUT_U8    1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_OUT_I8    1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_OUT_I16   1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_OUT_F32   1
#define EI_TFLITE_DISABLE_TreeEnsembleClassifier_OUT_BOOL  1

#endif // EI_TFLITE_MODEL_OPS_DEFINES_H
