// Generated by tools/export_policy.py -- do not edit.
//   actor  wheeledhand_walk.onnx
//   task   Wheeledhand-Walk
//   layers 68 -> 256 -> 128 -> 64 -> 19 (ELU)
//   checked against onnxruntime to 3.1e-06
//   control  30 Hz (overridden; calibration.yaml says 30)

#pragma once

#include <stdint.h>

// Shape of the network.
#define POLICY_WALK_OBS_DIM 68
#define POLICY_WALK_ACT_DIM 19
#define POLICY_WALK_LAYERS 4
#define POLICY_WALK_WIDEST_LAYER 256
// Floats in the weight matrices and biases together, so a build that
// copies them into RAM can size its buffer without a number typed in
// by hand that a retrain could make stale.
#define POLICY_WALK_WEIGHT_FLOATS 60051

// Control loop constants, taken from deploy_spec.json and
// calibration.yaml so the firmware cannot drift from the host tools.
#define POLICY_WALK_ACTION_SCALE 0.25f
#define POLICY_WALK_PHASE_PERIOD_S 0.6f
#define POLICY_WALK_PHASE_STAND_THRESHOLD 0.1f

// The command band the actor was actually trained on. Outside it the
// policy is extrapolating, and nothing in the observation tells it so
// -- it simply produces a target for a speed it has never had to
// achieve. The firmware clamps to these rather than to whatever the
// operator's stick can reach, which for one policy here was three
// times the trained speed.
#define POLICY_WALK_COMMAND_VX_MIN 0.0778866667f
#define POLICY_WALK_COMMAND_VX_MAX 0.155773333f
#define POLICY_WALK_COMMAND_WZ_MAX 0.0f
#define POLICY_WALK_COMMAND_RANGES_KNOWN 1
// Fraction of training environments that were given a zero command.
// Zero here means the actor has never been asked to stand still, so a
// stick at rest is outside what it was trained on.
#define POLICY_WALK_STANDING_FRACTION 0.0f

#define POLICY_WALK_CONTROL_HZ 30.0f
#define POLICY_WALK_SERVO_FRAME_COUNT 6
// Getting to the home stance before the policy starts: slow, because
// nothing about it is time-critical and the hand may be starting from
// a collapsed pose.
#define POLICY_WALK_HOME_FRAME_COUNT 200
// Holding stiffness written into every servo before running. The
// board comes set to 127, which buzzed on this hand.
#define POLICY_WALK_SERVO_STRETCH 90
#define POLICY_WALK_JOINT_VEL_WINDOW_S 0.08f

// Where each observation term starts, so the firmware assembles the
// vector in the order the actor was trained on rather than in the
// order it happens to compute the terms.
#define POLICY_WALK_OBS_BASE_ANG_VEL_START 0
#define POLICY_WALK_OBS_BASE_ANG_VEL_DIM 3
#define POLICY_WALK_OBS_PROJECTED_GRAVITY_START 3
#define POLICY_WALK_OBS_PROJECTED_GRAVITY_DIM 3
#define POLICY_WALK_OBS_COMMAND_START 6
#define POLICY_WALK_OBS_COMMAND_DIM 3
#define POLICY_WALK_OBS_PHASE_START 9
#define POLICY_WALK_OBS_PHASE_DIM 2
#define POLICY_WALK_OBS_JOINT_POS_START 11
#define POLICY_WALK_OBS_JOINT_POS_DIM 19
#define POLICY_WALK_OBS_JOINT_VEL_START 30
#define POLICY_WALK_OBS_JOINT_VEL_DIM 19
#define POLICY_WALK_OBS_ACTIONS_START 49
#define POLICY_WALK_OBS_ACTIONS_DIM 19

// Home pose in URDF radians: the action is an offset from this, and
// joint_pos is reported relative to it.
static const float kPolicyHomeRadWalk[19] = {
    0.0628649965f, 0.157441005f, 1.60426497f, 1.50615001f, -0.0446050018f, 0.292989999f, 1.60582805f, 1.34911501f,
    0.0204629991f, 0.364068002f, 1.60707295f, 1.27161598f, 0.0665479973f, 0.263628006f, 1.60445404f, 1.39231098f,
    0.0782769993f, 0.0230720006f, 0.00495600002f,
};

static const float kPolicyJointLowRadWalk[19] = {
    -1.5f, -0.698000014f, -1.77999997f, -1.77999997f, -1.5f, -0.698000014f, -1.77999997f, -1.77999997f,
    -1.5f, -0.698000014f, -1.77999997f, -1.77999997f, -1.5f, -0.698000014f, -1.77999997f, -1.77999997f,
    -2.35599995f, -1.77999997f, -1.77999997f,
};

static const float kPolicyJointHighRadWalk[19] = {
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    2.35599995f, 1.77999997f, 1.77999997f,
};

// RCB-4 servo id per joint, in joint_order. NOT sorted: this is the
// policy's own order, and the board wants ids ascending, so a caller
// writing a servo command has to reorder.
static const uint8_t kPolicyServoIdsWalk[19] = {
    6, 4, 2, 20, 30, 28, 34, 26, 27, 25, 23, 13, 17, 15, 1, 11,
    33, 9, 19,
};

// Gravity in the root frame for this policy's own stance, from
// home_base.quat_wxyz. Used only when there is no IMU; a transition
// changes the attitude and cannot be represented by it at all.
static const float kPolicyStanceGravityWalk[3] = {
    -0.340788145f, -0.00161169018f, -0.940138741f,
};

// v_gyro = R_root_to_gyro @ v_root. base_ang_vel is observed in the
// URDF base link frame while projected_gravity is in root, and the
// two are not the same frame -- getting this wrong is silent.
static const float kPolicyRootToGyroWalk[9] = {
    -0.0f, -1.0f, 0.0f, -0.0f, 0.0f, -1.0f, 1.0f, -0.0f,
    -0.0f,
};
