// Generated by tools/export_policy.py -- do not edit.
//   actor  walk.onnx
//   task   Handrobot-Crawl-Flat
//   layers 68 -> 256 -> 128 -> 64 -> 19 (ELU)
//   checked against onnxruntime to 1.34e-05
//   control  30 Hz (overridden; calibration.yaml says 40)

#pragma once

#include <stdint.h>

// Shape of the network.
#define POLICY_OBS_DIM 68
#define POLICY_ACT_DIM 19
#define POLICY_LAYERS 4
#define POLICY_WIDEST_LAYER 256
// Floats in the weight matrices and biases together, so a build that
// copies them into RAM can size its buffer without a number typed in
// by hand that a retrain could make stale.
#define POLICY_WEIGHT_FLOATS 60051

// Control loop constants, taken from deploy_spec.json and
// calibration.yaml so the firmware cannot drift from the host tools.
#define POLICY_ACTION_SCALE 0.25f
#define POLICY_PHASE_PERIOD_S 0.6f
#define POLICY_PHASE_STAND_THRESHOLD 0.1f
#define POLICY_CONTROL_HZ 30.0f
#define POLICY_SERVO_FRAME_COUNT 6
// Getting to the home stance before the policy starts: slow, because
// nothing about it is time-critical and the hand may be starting from
// a collapsed pose.
#define POLICY_HOME_FRAME_COUNT 50
// Holding stiffness written into every servo before running. The
// board comes set to 127, which buzzed on this hand.
#define POLICY_SERVO_STRETCH 90
#define POLICY_JOINT_VEL_WINDOW_S 0.08f

// Where each observation term starts, so the firmware assembles the
// vector in the order the actor was trained on rather than in the
// order it happens to compute the terms.
#define POLICY_OBS_BASE_ANG_VEL_START 0
#define POLICY_OBS_BASE_ANG_VEL_DIM 3
#define POLICY_OBS_PROJECTED_GRAVITY_START 3
#define POLICY_OBS_PROJECTED_GRAVITY_DIM 3
#define POLICY_OBS_COMMAND_START 6
#define POLICY_OBS_COMMAND_DIM 3
#define POLICY_OBS_PHASE_START 9
#define POLICY_OBS_PHASE_DIM 2
#define POLICY_OBS_JOINT_POS_START 11
#define POLICY_OBS_JOINT_POS_DIM 19
#define POLICY_OBS_JOINT_VEL_START 30
#define POLICY_OBS_JOINT_VEL_DIM 19
#define POLICY_OBS_ACTIONS_START 49
#define POLICY_OBS_ACTIONS_DIM 19

// Home pose in URDF radians: the action is an offset from this, and
// joint_pos is reported relative to it.
static const float kPolicyHomeRad[19] = {
    -1.29995894f, 0.697046995f, 0.548991024f, 0.400169998f, -0.433328986f, 0.697046995f, 0.548991024f, 0.400169998f,
    0.433333993f, 0.697046995f, 0.548991024f, 0.400169998f, 1.29998004f, 0.697046995f, 0.548991024f, 0.400169998f,
    1.49864197f, 0.915534973f, 0.00681299996f,
};

static const float kPolicyJointLowRad[19] = {
    -1.5f, -0.698000014f, 0.0f, -0.698000014f, -1.5f, -0.698000014f, 0.0f, -0.698000014f,
    -1.5f, -0.698000014f, 0.0f, -0.698000014f, -1.5f, -0.698000014f, 0.0f, -0.698000014f,
    -2.35599995f, -0.698000014f, -0.698000014f,
};

static const float kPolicyJointHighRad[19] = {
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    1.5f, 1.57000005f, 1.77999997f, 1.77999997f, 1.5f, 1.57000005f, 1.77999997f, 1.77999997f,
    2.35599995f, 1.77999997f, 1.77999997f,
};

// RCB-4 servo id per joint, in joint_order. NOT sorted: this is the
// policy's own order, and the board wants ids ascending, so a caller
// writing a servo command has to reorder.
static const uint8_t kPolicyServoIds[19] = {
    6, 4, 2, 20, 30, 28, 34, 26, 27, 25, 23, 13, 17, 15, 1, 11,
    33, 9, 19,
};
